gantt
    title Répartition des tâches
    dateFormat  YYYY-MM-DD
    axisFormat %d/%m

    section Antonin
    Code noising et des patchs :ant1, 2025-04-22, 1d
    Implémentation MoyCov et ACP :ant2, 2025-04-23, 1d
    Fonctions de seuillage et calculs performances :ant3, 2025-05-12, 4d
    Correction et optimisation du code :ant4, 2025-05-19, 4d
    Péparation soutenance :ant5, 2025-05-26, 2d
    Soutenance :ant6, 2025-05-28, 1d

    section Clément
    Analyse UML :cle1, 2025-04-22, 2d
    Ecriture livrable 1 :cle2, 2025-04-22, 2d
    Mathématiques :cle3, 2025-04-23, 1d
    Démonstration mathématiques :cle4, 2025-05-12, 1d
    Configuration Eclipse : cle5, 2025-05-13, 1d
    Ecriture manuel :cle6, 2025-05-14, 2d
    Ecriture du rapport final :cle7, 2025-05-19, 4d
    Péparation soutenance :cle8, 2025-05-26, 2d
    Soutenance :cle9, 2025-05-28, 1d

    section Mathias
    Ecriture livrable 1 :mth1, 2025-04-22, 2d
    Mathématiques :mth2, 2025-04-23, 1d
    Fonction ACP local et retouche du Main : mth3, 2025-05-13, 3d
    Ecriture manuel :mth4, 2025-05-15, 1d
    Correction et optimisation du code :mth5, 2025-05-19, 4d
    Péparation soutenance :mth6, 2025-05-26, 2d
    Soutenance :mth7, 2025-05-28, 1d

    section Mattias
    Analyse UML :mtt1, 2025-04-22, 2d
    Maquettage :mtt2, 2025-04-22, 2d
    Diagramme Gantt :mtt3, 2025-04-22, 2d
    Ecriture livrable 1 :mtt4, 2025-04-22, 2d
    Javadoc : mtt5, 2025-05-13, 3d
    Révisions diagrammes : mtt6, 2025-05-12, 1d
    Ecriture du rapport final :mtt7, 2025-05-19, 4d
    Péparation soutenance :mtt8, 2025-05-26, 2d
    Soutenance :mtt9, 2025-05-28, 1d


    section Thomas
    Création GitHub :tho1, 2025-04-22, 1d
    Gestion base d'image :tho2, 2025-04-22, 1d
    Code noising et des patchs :tho3, 2025-04-23, 1d
    Construction IHM : tho4, 2025-04-23, 1d
    Implémentation du code dans l'IHM : tho5, 2025-05-12, 4d
    Finition sur l'IHM : tho6, 2025-05-19, 4d
    Péparation soutenance :tho7, 2025-05-26, 2d
    Soutenance :tho8, 2025-05-28, 1d

    section Timeline
    Début Phase 1 :milestone mil1, 2025-04-22, 0d
    Fin Phase 1 :milestone mil2, 2025-04-24, 0d
    Début Phase 2 :milestone mil3, 2025-05-12, 0d
    Fin Phase 2 :milestone mil4, 2025-05-15, 0d
    Début Phase 3 :milestone mil5, 2025-05-19, 0d
    Fin Phase 3 :milestone mil6, 2025-05-22, 0d
    Début Phase 4 :milestone mil7, 2025-05-26, 0d
    Fin Phase 4 :milestone mil8, 2025-05-28, 0d
