gantt
    title Répartition des tâches
    dateFormat  YYYY-MM-DD
    axisFormat %d/%m

    section Antonin
    Code noising et des patchs :a3, 2025-04-22, 1d
    Implémentation MoyCov et ACP :a10, 2025-04-23, 1d

    section Clément
    Analyse UML :a1, 2025-04-22, 2d
    Ecriture livrable 1 :a2, 2025-04-22, 2d
    Mathématiques :a11, 2025-04-23, 1d

    section Mathias
    Ecriture livrable 1 :a8, 2025-04-22, 2d
    Mathématiques :a9, 2025-04-23, 1d

    section Mattias
    Analyse UML :a14, 2025-04-22, 2d
    Maquettage :a6, 2025-04-22, 2d
    Diagramme Gantt :a7, 2025-04-22, 2d
    Ecriture livrable 1 :a18, 2025-04-22, 2d

    section Thomas
    Création GitHub :a4, 2025-04-22, 1d
    Gestion base d'image :a5, after a4, 1d
    Code noising et des patchs :a15, 2025-04-23, 1d
    Construction IHM : a16, 2025-04-23, 1d

    section Timeline
    Début Phase 1 :milestone m1, 2025-04-22, 0d
    Fin Phase 1 :milestone m2, 2025-04-24, 0d
