gantt
    title Répartition des tâches
    dateFormat  YYYY-MM-DD
    axisFormat %d/%m

    section Antonin
    Code noising et des patchs :ant1, 2025-04-22, 1d
    Implémentation MoyCov et ACP :ant2, 2025-04-23, 1d
    Fonctions de seuillage et calcul performance :ant3, 2025-05-12, 4d
    
    section Clément
    Analyse UML :cle1, 2025-04-22, 2d
    Ecriture livrable 1 :cle2, 2025-04-22, 2d
    Mathématiques :cle3, 2025-04-23, 1d
    Démonstration mathématiques :cle4, 2025-05-12, 1d
    Configuration Eclipse : cle5, 2025-05-13, 1d
    Ecriture manuel :cle6, 2025-05-14, 2d
    
    section Mathias
    Ecriture livrable 1 :mth1, 2025-04-22, 2d
    Mathématiques :mth2, 2025-04-23, 1d
    Fonction ACP local et retouche du Main : mth3, 2025-05-13, 3d
    Ecriture manuel :mth, 2025-05-15, 1d
    
    section Mattias
    Analyse UML :mtt1, 2025-04-22, 2d
    Maquettage :mtt2, 2025-04-22, 2d
    Diagramme Gantt :mtt3, 2025-04-22, 2d
    Ecriture livrable 1 :mtt4, 2025-04-22, 2d
    Javadoc : mtt5, 2025-05-13, 3d
    Révisions diagrammes : mtt6, 2025-05-12, 1d
    
    section Thomas
    Création GitHub :tho1, 2025-04-22, 1d
    Gestion base d'image :tho2, 2025-04-22, 1d
    Code noising et des patchs :tho3, 2025-04-23, 1d
    Construction IHM : tho4, 2025-04-23, 1d
    Implémentation du code dans l'IHM : tho5, 2025-05-12, 4d
    
    section Timeline
    Début Phase 1 :milestone mil1, 2025-04-22, 0d
    Fin Phase 1 :milestone mil2, 2025-04-24, 0d
    Début Phase 2 :milestone mil3, 2025-05-12, 0d
    Fin Phase 2 :milestone mil4, 2025-05-15, 0d
